### ISSUE TITLE
Exception when starting VMware VM on Windows

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-server#1919]
This is a regression, was working in version 2.2.21

```
2021-06-12 23:07:50 ERROR route.py:242 Uncaught exception detected: <class 'AttributeError'>
Traceback (most recent call last):
  File "./gns3-server\gns3server\web\route.py", line 198, in control_schema
  File "./gns3-server\gns3server\handlers\api\compute\vmware_handler.py", line 157, in start
  File "./gns3-server\gns3server\compute\vmware\vmware_vm.py", line 457, in start
  File "./gns3-server\gns3server\compute\vmware\vmware_vm.py", line 262, in _set_network_options
  File "./gns3-server\gns3server\compute\vmware\__init__.py", line 370, in refresh_vmnet_list
AttributeError: 'list' object has no attribute 'keys'
2021-06-12 23:07:50 INFO crash_report.py:166 Crash report sent with event ID: c39446b805ad41a0bdc1be7e11765bbf
2021-06-12 23:07:50 INFO web_log.py:206 127.0.0.1 [12/Jun/2021:15:07:49 +0000] "POST /v2/compute/projects/797f7b21-d4a6-4712-bc0e-4d3c50d25b00/vmware/nodes/c9fc1b86-c387-4951-9657-6b534dc9f057/start HTTP/1.1" 500 860 "-" "Python/3.6 aiohttp/3.7.4.post0"
2021-06-12 23:07:50 INFO web_log.py:206 127.0.0.1 [12/Jun/2021:15:07:49 +0000] "POST /v2/projects/797f7b21-d4a6-4712-bc0e-4d3c50d25b00/nodes/start HTTP/1.1" 500 423 "-" "GNS3 QT Client v2.2.22"
```

**Comment by grossmj** [comment]
Fixed.
