### ISSUE TITLE
gns3server fails to start with Fedora 37 Python 3.11.0rc2

### ISSUE THREAD

**Issue by nuqleo** [GNS3/gns3-server#2129]
$ gns3server 
Traceback (most recent call last):
  File "/usr/bin/gns3server", line 33, in <module>
    sys.exit(load_entry_point('gns3-server==2.2.34', 'console_scripts', 'gns3server')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gns3server/main.py", line 81, in main
    from gns3server.run import run
  File "/usr/lib/python3.11/site-packages/gns3server/run.py", line 31, in <module>
    from gns3server.web.web_server import WebServer
  File "/usr/lib/python3.11/site-packages/gns3server/web/web_server.py", line 45, in <module>
    import gns3server.handlers
  File "/usr/lib/python3.11/site-packages/gns3server/handlers/__init__.py", line 18, in <module>
    from gns3server.handlers.index_handler import IndexHandler
  File "/usr/lib/python3.11/site-packages/gns3server/handlers/index_handler.py", line 28, in <module>
    class IndexHandler:
  File "/usr/lib/python3.11/site-packages/gns3server/handlers/index_handler.py", line 30, in IndexHandler
    @Route.get(
     ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gns3server/web/route.py", line 167, in register
    func = asyncio.coroutine(func)
           ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?

$ python3 --version
Python 3.11.0rc2

**Comment by nuqleo** [comment]
This commit fixed error
https://github.com/GNS3/gns3-server/commit/2d74d1ad94fa3ae48651778a89918524c7910dfb

**Comment by grossmj** [comment]
Indeed, the next release will work with Python 3.11
